-- BimaResto - Neon PostgreSQL Initialization Script
-- Run this file in Neon SQL Editor or via psql.

BEGIN;

-- Optional but useful if you want UUID/util functions later.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================
-- Compatibility Fixes (Existing DB)
-- =========================
-- If older schema used table_id, rename it to tables_id to match current backend model.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'orders'
      AND column_name = 'table_id'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'orders'
      AND column_name = 'tables_id'
  ) THEN
    EXECUTE 'ALTER TABLE orders RENAME COLUMN table_id TO tables_id';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'payments'
      AND column_name = 'table_id'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'payments'
      AND column_name = 'tables_id'
  ) THEN
    EXECUTE 'ALTER TABLE payments RENAME COLUMN table_id TO tables_id';
  END IF;
END $$;

DROP INDEX IF EXISTS idx_orders_table_id;
DROP INDEX IF EXISTS idx_payments_table_id;

-- =========================
-- Core Master Tables
-- =========================

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS staffs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INTEGER NOT NULL REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  full_name TEXT NOT NULL,
  username TEXT UNIQUE,
  email TEXT UNIQUE,
  phone TEXT,
  password_hash TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id INTEGER NOT NULL REFERENCES staffs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_staff_id ON refresh_tokens(staff_id);

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS menus (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categories_id INTEGER NOT NULL REFERENCES categories(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(12,2) NOT NULL,
  is_available BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_menus_categories_id ON menus(categories_id);

CREATE TABLE IF NOT EXISTS tables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_number TEXT NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 4,
  status TEXT NOT NULL DEFAULT 'available',
  CONSTRAINT chk_tables_status CHECK (status IN ('available', 'occupied', 'reserved'))
);

-- =========================
-- Transactional Tables
-- =========================

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tables_id INTEGER NOT NULL REFERENCES tables(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  staff_id INTEGER NOT NULL REFERENCES staffs(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  source TEXT NOT NULL DEFAULT 'dine_in',
  status TEXT NOT NULL DEFAULT 'pending',
  notes TEXT,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax NUMERIC(12,2) NOT NULL DEFAULT 0,
  service_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  client_ref_id TEXT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_orders_source CHECK (source IN ('dine_in', 'dine-in', 'takeaway', 'delivery')),
  CONSTRAINT chk_orders_status CHECK (status IN ('pending', 'cooking', 'served', 'completed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_orders_tables_id ON orders(tables_id);
CREATE INDEX IF NOT EXISTS idx_orders_staff_id ON orders(staff_id);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  menu_id INTEGER NOT NULL REFERENCES menus(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  is_paid BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
  CONSTRAINT chk_order_items_status CHECK (status IN ('pending', 'cooking', 'served', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_menu_id ON order_items(menu_id);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  tables_id INTEGER NOT NULL REFERENCES tables(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  staff_id INTEGER NOT NULL REFERENCES staffs(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  total NUMERIC(12,2) NOT NULL,
  amount_paid NUMERIC(12,2) NOT NULL,
  change NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL,
  payment_status TEXT NOT NULL,
  paid_at TIMESTAMPTZ,
  CONSTRAINT chk_payments_method CHECK (payment_method IN ('cash', 'qris', 'debit', 'credit', 'card', 'e-wallet', 'transfer')),
  CONSTRAINT chk_payments_status CHECK (payment_status IN ('pending', 'paid', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);

CREATE TABLE IF NOT EXISTS split_bills (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_split_bills_order_id ON split_bills(order_id);

CREATE TABLE IF NOT EXISTS promos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  promo_type TEXT NOT NULL DEFAULT 'bundle',
  buy_menu_id INTEGER NOT NULL REFERENCES menus(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  free_menu_id INTEGER NOT NULL REFERENCES menus(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  buy_quantity INTEGER NOT NULL DEFAULT 1,
  free_quantity INTEGER NOT NULL DEFAULT 1,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  -- Legacy fields still present in backend model for compatibility.
  code TEXT,
  discount NUMERIC(12,2),
  active BOOLEAN,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_promos_type CHECK (promo_type IN ('bundle')),
  CONSTRAINT chk_promos_buy_qty CHECK (buy_quantity > 0),
  CONSTRAINT chk_promos_free_qty CHECK (free_quantity > 0),
  CONSTRAINT chk_promos_date_range CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_promos_buy_menu_id ON promos(buy_menu_id);
CREATE INDEX IF NOT EXISTS idx_promos_free_menu_id ON promos(free_menu_id);

-- =========================
-- Seed Data
-- =========================

INSERT INTO roles (id, name) VALUES
  (1, 'admin'),
  (2, 'kasir'),
  (3, 'kitchen'),
  (4, 'manager')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- Create default admin using bcrypt generated in PostgreSQL.
-- Password: admin123
INSERT INTO staffs (id, role_id, full_name, username, email, phone, password_hash, is_active)
VALUES (
  1,
  1,
  'John Admin',
  'admin',
  'admin@bimaresto.com',
  '+62 812-3456-7890',
  crypt('admin123', gen_salt('bf')),
  TRUE
)
ON CONFLICT (id) DO UPDATE SET
  role_id = EXCLUDED.role_id,
  full_name = EXCLUDED.full_name,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

INSERT INTO tables (id, table_number, status, capacity) VALUES
  (1, '1', 'available', 4),
  (2, '2', 'available', 2),
  (3, '3', 'available', 6)
ON CONFLICT (id) DO UPDATE SET
  table_number = EXCLUDED.table_number,
  status = EXCLUDED.status,
  capacity = EXCLUDED.capacity;

COMMIT;
